language: python
python:
  - "3.6"

before_install:
  - pip install --upgrade pip
  - export FLASK_APP=run.py
  - export APP_DIRECTORY=app

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - flake8 $APP_DIRECTORY --ignore=E402
  - flask test