language: python
python:
  - "3.6"

before_install:
  - pip install --upgrade pip
  - export FLASK_APP=run.py
  - export APP_DIRECTORY=app

install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install autopep8

script:
  - autopep8 -i -r $APP_DIRECTORY
  - pycodestyle $APP_DIRECTORY --ignore=E402
  - flask test